import type { Metadata } from "next";
import {Inter, Poppins, Great_Vibes, Miniver} from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets:["latin"],
  weight: ['100', '200', '300', '400','500', '600','700', '800','900'],
  variable: '--font-poppins',
})

const inter = Inter({
  subsets:["latin"],
  weight: ['100', '200', '300', '400','500', '600','700', '800','900'],
  variable: '--font-inter',
})

const great_vibes = Great_Vibes({
  subsets:["latin"],
  weight: ['400'],
  variable: '--font-great_vibes',
})

const miniver = Miniver({
  subsets:["latin"],
  weight: ['400'],
  variable: '--font-miniver',
})

export const metadata: Metadata = {
  title: "E-Commerce Website Hackathon",
  description: "Generated by S. M. Essa Abbas Zaidi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} ${great_vibes.variable} ${miniver.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
